### ISSUE TITLE
Crash on release mode

### ISSUE THREAD

**Issue by abodamin** [liyuanhust/flutter_simple_pdf_viewer#2]
app is crashing when I open the PDF on release mode , but it works fine in debug mode
I've already added this code to my gradle. 
`
 release {
            ndk {
                abiFilters "armeabi-v7a", "x86"
            }
      }
`

**Comment by binSaed** [comment]
Hi Abdullah,
this package uses AndroidPdfViewer
so if u use proguard you should include this line 
`-keep class com.shockwave.**`

u can take a look in my package to know how to make it **_if u need_**

https://github.com/AbdOoSaed/flutter_cached_pdfview#for-production-usage

**Comment by abodamin** [comment]
Thanks Mr Abdullah Saed, that actually fixed the problem
appreciated.

and for those who might face same thing just follow next steps:

1 - Go to [this](https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/master/example/android/app/proguard-rules.pro) link and copy file (or create it) in the same distination under app ( `app/proguard-rules.pro` ) same level of `app/build.gradle`.

2 - Go to `app/build.gradle` and add the follwing lines of code under your `buildTypes{ }` :
`
release {
            signingConfig signingConfigs.release
            minifyEnabled true 
            shrinkResources true
            useProguard true
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
`
3 - Make sure to clean your project and run on release mode .. `flutter clean; flutter build apk; flutter install ` would do the trick for u ;)

Regards.

**Comment by Colir** [comment]
@abodamin @AbdOoSaed Hi. i've the same problem (app crash on release mode). However the proguard-rules.pro file doesn't exist anymore on @AbdOoSaed project. Can you help me ? Thank you very much

**Comment by binSaed** [comment]
@Colir  sorry for that I deleted the file by mistake
u can get proguard-rules.pro from this link
https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/ad017c2b9d150b2c50dd43ad08fa809970bc66b5/example/android/app/proguard-rules.pro

**Comment by Colir** [comment]
@abodamin @AbdOoSaed A big thank to you guys !
